# Generated by Django 5.2.7 on 2025-11-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(help_text='출판사명 (UNIQUE, NOT NULL)', max_length=255, unique=True),
        ),
    ]
